name: build
on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Check formatting
        run: crystal tool format --check
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec
