name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '20 16 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Check formatting
        run: crystal tool format --check
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec -v
